import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const CheckoutSessionFailure: NextPage = () => {
  return (
    <>
      <Head>
        <title>Product | Success</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Failure...</p>
        <Link href={"/"}>Go Back Home</Link>
      </main>
    </>
  );
};

export default CheckoutSessionFailure;
