import { type NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import { api } from "../../utils/api";
import { useRouter } from "next/router";

const CheckoutSessionSuccess: NextPage = () => {
  const router = useRouter();
  const checkoutSessionId = router.query.checkout_session_id as string;

  const { data } = api.stripe.checkoutSession.useQuery(
    { checkoutSessionId },
    {
      enabled: !!checkoutSessionId,
    }
  );

  return (
    <>
      <Head>
        <title>Product | Success</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: 16 }}>
        <p>Success!!</p>
        {data && !data.customer.deleted ? (
          <div>
            <p>customerId: {data.customer.id}</p>
            <p>name: {data.customer.name}</p>
            <p>email: {data.customer.email}</p>
          </div>
        ) : (
          <div>
            <p>customerId: {data?.customer.id}</p>
            <p>name:</p>
            <p>email:</p>
          </div>
        )}
        <Link href={"/"}>Go Back Home</Link>
      </main>
    </>
  );
};

export default CheckoutSessionSuccess;
