import { useCallback, useEffect, useRef } from "react";

import type { NextPage } from "next";
import Head from "next/head";
import type Stripe from "stripe";

import { api } from "../utils/api";

const APP_USER_ID_LIST = ["test_1", "test_2", "test_3", "test_4"];

const Home: NextPage = () => {
  const appUserIdSelectRef = useRef<HTMLSelectElement>(null);

  const { data } = api.stripe.products.useQuery();
  const mutation = api.stripe.createCheckoutSession.useMutation();

  const handleClick = useCallback(
    (product: Stripe.Product) => {
      const appUserId = appUserIdSelectRef.current?.value;
      const priceId = product.default_price;

      if (!appUserId || !priceId) {
        throw new Error("Requires appUserId and priceId");
      }

      mutation.mutate({
        appUserId,
        priceId: typeof priceId === "string" ? priceId : priceId.id,
      });
    },
    [mutation]
  );

  useEffect(() => {
    if (mutation.data?.checkoutSessionUrl) {
      window.location.href = mutation.data?.checkoutSessionUrl;
    }
  }, [mutation.data?.checkoutSessionUrl]);

  return (
    <>
      <Head>
        <title>{`Suburi Stripe App | Home`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: "16px 0" }}>
        <p style={{ marginLeft: 40 }}>Email</p>
        <select
          ref={appUserIdSelectRef}
          size={APP_USER_ID_LIST.length}
          defaultValue={APP_USER_ID_LIST[0]}
          style={{ marginLeft: 40, padding: 8, fontSize: 16 }}
        >
          {APP_USER_ID_LIST.map((appUserId, i) => {
            return (
              <option key={appUserId} value={appUserId} style={{ padding: 4 }}>
                {appUserId}
              </option>
            );
          })}
        </select>

        <ul style={{ listStyleType: "none" }}>
          {data?.products.map((product) => {
            return (
              <li
                key={product.id}
                style={{
                  margin: "16px 0",
                }}
              >
                <button
                  type="button"
                  onClick={() => handleClick(product)}
                  style={{
                    border: "1px solid gray",
                    padding: "0 16px",
                    cursor: "pointer",
                  }}
                >
                  <p>ID: {product.id}</p>
                  <p>Name: {product.name}</p>
                  <p>PriceID: {product.default_price as string}</p>
                </button>
              </li>
            );
          })}
        </ul>
      </main>
    </>
  );
};

export default Home;
